apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dynamicpickerexample
  title: Repository Picker
  description: Repository Picker
spec:
  owner: khushi.sharma@harness.io
  type: service
  parameters:
    - title: Repo Picker
      properties:
        gitusername:
          title: Github username
          description: Enter your Github username
          type: string
        repoName:
          title: Repository name
          type: string
        topicList: 
          type: array
          title: topics
          items:
            type: string
          ui:widget: textarea
        custom1:
          title: Repository Topics
          type: string
          description: Select or update repository topics
          ui:field: SelectFieldFromApi
          ui:options:
            path: proxy/github-api/repos/{{parameters.ownerName}}/{{parameters.repoName}}/topics
            request:
              method: PUT
              headers:
                Accept: application/vnd.github+json
                Content-Type: application/json
            body:
              names: "{{parameters.topicList}}"         
  steps:
    - id: trigger
      name: Writing the GitSync Variable
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/module/idp-admin/orgs/default/projects/idpprojectsc/pipelines/DummyPipeline/pipeline-studio/?storeType=INLINE&stageId=DummyStage&sectionId=EXECUTION
        inputset: 
          "username": ${{ parameters.username }}
          "name": ${{ parameters.name }}
          "pipeline.stages.GitsyncStageTemplate.variables.greetings": ${{ parameters['pipeline.stages.GitsyncStageTemplate.variables.greetings'] }}
        apikey: ${{ parameters.token }}
        enableVariableMapping: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
